name: Rust Tests and MSRV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Parse MSRV from manifest
      id: msrv
      run: |
        MSRV=$(grep -oP 'rust-version\s*=\s*"\K[0-9.]+(?=")' Cargo.toml)
        echo "MSRV version: $MSRV"
        echo "::set-output name=msrv::$MSRV"

    - name: Set up Rust toolchain for MSRV
      run: |
        rustup install ${{ steps.msrv.outputs.msrv }}
        rustup override set ${{ steps.msrv.outputs.msrv }}

    - name: Check all targets with MSRV
      run: cargo check --all-targets && cargo check --release --all-targets
      
    - name: Run tests with MSRV
      run: cargo test --verbose
      
    - name: Switch to stable and run Clippy
      run: |
        rustup default stable
        rustup component add clippy
        cargo clippy -- -D warnings