name: Rust Tests and MSRV
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-audit,cargo-deny

    - name: Parse MSRV from manifest
      id: msrv
      run: |
        MSRV=$(grep -oP 'rust-version\s*=\s*"\K[0-9.]+(?=")' Cargo.toml)
        echo "MSRV version: $MSRV"
        echo "msrv=$MSRV" >> $GITHUB_OUTPUT

    - name: Set up Rust toolchain for MSRV
      run: |
        rustup install ${{ steps.msrv.outputs.msrv }}
        rustup override set ${{ steps.msrv.outputs.msrv }}
    
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check all targets with MSRV
      run: cargo check --all-targets && cargo check --release --all-targets
      
    - name: Run tests with MSRV
      run: cargo test --verbose --no-fail-fast
    
    - name: Run tests for mint feature
      run: cargo test mint --features mint
      
    - name: Switch to stable and run Clippy
      if: always()
      run: |
        rustup override unset
        rustup component add clippy rustfmt
        cargo clippy --verbose -- -D warnings

    - name: Check cargo docs
      if: always()
      run: |
        export RUSTDOCFLAGS="-D warnings"
        cargo doc --no-deps --document-private-items --verbose

    - name: Check formatting
      if: always()
      run: |
        cargo fmt --all -- --check

    - name: Run cargo audit
      if: always()
      run: cargo audit --deny=warnings
        
    - name: Run cargo deny
      if: always()
      run: cargo deny check --deny=warnings